=== usgin/geochemBuildingBlocks/build/annotated/bbr/metadata/geochemProperties/spatialRegistration/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Spatial Registration Type",
  "description": "Defines pixel coordinate system registration including origin coordinates, pixel scales, and coordinate definition type for spatially registered images and maps.",
  "type": "object",
  "properties": {
    "ada:basemap": {
      "type": "string",
      "description": "link to appropriate basemap image map"
    },
    "ada:originX": {
      "type": "number"
    },
    "ada:originY": {
      "type": "number"
    },
    "ada:originZ": {
      "type": "number"
    },
    "ada:coordDef": {
      "type": "string",
      "description": "Whether coordinates are stage-defined or pixel-defined. If pixel-defined, are coordinates from stage, upperleftPixel, or centerPixel."
    },
    "ada:coordUnits": {
      "type": "string"
    },
    "ada:pixelUnits": {
      "type": "string"
    },
    "ada:pixelScaleX": {
      "type": "number"
    },
    "ada:pixelScaleY": {
      "type": "number"
    },
    "ada:originLocation": {
      "type": "string",
      "description": "The location of the origin pixel of an image. Range: upperLeft, upperRight, lowerLeft, lowerRight, center"
    }
  },
  "required": [
    "ada:originX",
    "ada:originY",
    "ada:pixelScaleX",
    "ada:pixelScaleY",
    "ada:pixelUnits",
    "ada:originLocation",
    "ada:coordDef"
  ],
  "x-jsonld-prefixes": {
    "ada": "https://ada.astromat.org/metadata/"
  }
}

=== usgin/geochemBuildingBlocks/build/tests/bbr/metadata/adaProperties/spatialRegistration/example_1_1.json
{
  "ada:basemap": "basemap_BSE_001.tif",
  "ada:originX": 0.0,
  "ada:originY": 0.0,
  "ada:originZ": 0.0,
  "ada:coordDef": "pixel-defined",
  "ada:coordUnits": "micrometer",
  "ada:pixelUnits": "micrometer",
  "ada:pixelScaleX": 0.125,
  "ada:pixelScaleY": 0.125,
  "ada:originLocation": "upperLeft"
}
