=== usgin/geochemBuildingBlocks/build/annotated/bbr/metadata/adaProperties/detailVNMIR/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "VNMIR Instrument Detail",
  "description": "Very-Near Mid-IR spectroscopy with detailed measurement parameters",
  "type": "object",
  "properties": {
    "@type": {
      "anyOf": [
        {
          "const": "ada:VNMIRSpectralPoint"
        },
        {
          "const": "ada:VNMIROverviewImage"
        },
        {
          "const": "ada:VNMIRSpectralMap"
        }
      ]
    },
    "ada:detector": {
      "type": "string"
    },
    "ada:beamsplitter": {
      "type": "string"
    },
    "ada:calibrationStandards": {
      "type": "string"
    },
    "ada:comments": {
      "type": "string"
    },
    "ada:numberOfScans": {
      "type": "integer"
    },
    "ada:eMaxFitRegionMax": {
      "type": "string"
    },
    "ada:eMaxFitRegionMin": {
      "type": "string"
    },
    "ada:emissionAngle": {
      "type": "number"
    },
    "ada:emissivityMaximum": {
      "type": "string"
    },
    "ada:environmentalPressure": {
      "type": "number"
    },
    "ada:incidenceAngle": {
      "type": "number"
    },
    "ada:measurement": {
      "type": "string"
    },
    "ada:measurementEnvironment": {
      "type": "string"
    },
    "ada:phaseAngle": {
      "type": "number"
    },
    "ada:sampleHeated": {
      "type": "boolean"
    },
    "ada:samplePreparation": {
      "type": "string"
    },
    "ada:sampleTemperature": {
      "type": "integer"
    },
    "ada:spectralRangeMax": {
      "type": "string"
    },
    "ada:spectralRangeMin": {
      "type": "string"
    },
    "ada:spectralResolution": {
      "type": "string"
    },
    "ada:spectralSampling": {
      "type": "string"
    },
    "ada:spotSize": {
      "type": "string"
    },
    "ada:uncertaintyNoise": {
      "type": "number"
    },
    "ada:vacuumExposedSample": {
      "type": "boolean"
    }
  },
  "x-jsonld-prefixes": {
    "schema": "http://schema.org/",
    "ada": "https://ada.astromat.org/metadata/"
  }
}

=== usgin/geochemBuildingBlocks/build/tests/bbr/metadata/adaProperties/detailVNMIR/example_1_1.json
{
  "@type": "ada:VNMIRSpectralPoint",
  "ada:detector": "MCT",
  "ada:beamsplitter": "KBr",
  "ada:calibrationStandards": "gold mirror",
  "ada:numberOfScans": 256,
  "ada:spectralRangeMin": "400",
  "ada:spectralRangeMax": "4000",
  "ada:spectralResolution": "4 cm-1",
  "ada:spectralSampling": "2 cm-1",
  "ada:spotSize": "100 micrometer",
  "ada:measurement": "reflectance",
  "ada:measurementEnvironment": "ambient",
  "ada:environmentalPressure": 1013.25,
  "ada:sampleHeated": false,
  "ada:sampleTemperature": 25,
  "ada:vacuumExposedSample": false,
  "ada:emissionAngle": 0.0,
  "ada:incidenceAngle": 30.0,
  "ada:phaseAngle": 30.0,
  "ada:uncertaintyNoise": 0.002
}
