=== usgin/geochemBuildingBlocks/_sources/geochemProperties/collection/collectionStructuredSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Collection Type",
  "description": "A collection can be a set of files with identical information model and serialization/formatting, or a heterogeneous set of files that together constitute a dataset (a composite dataset).",
  "type": "object",
  "properties": {
    "@type": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 2,
      "allOf": [
        {
          "contains": {
            "const": "ada:collection"
          }
        },
        {
          "contains": {
            "const": "https://schema.org/Collection"
          }
        }
      ],
      "description": "GeneralType for collections"
    },
    "ada:componentType": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string",
          "enum": [
            "ada:AIVAImageCollection",
            "ada:ARGTCollection",
            "ada:EAIRMSCollection",
            "ada:EMPAImageCollection",
            "ada:GCMSCollection",
            "ada:GCGCMSCollection",
            "ada:LCMSCollection",
            "ada:LCMSMSCollection",
            "ada:LIT2DDataCollection",
            "ada:LITPolarDataCollection",
            "ada:MCICPMSCollection",
            "ada:NanoIRMapCollection",
            "ada:NanoIRPointCollection",
            "ada:NanoSIMSCollection",
            "ada:NanoSIMSImageCollection",
            "ada:QRISCalibratedCollection",
            "ada:QRISRawCollection",
            "ada:RITOFNGMSCollection",
            "ada:SEMEDSElementalMaps",
            "ada:SEMEDSPointDataCollection",
            "ada:SEMImageCollection",
            "ada:SIMSCollection",
            "ada:TEMEDSImageCollection",
            "ada:TOFSIMSCollection",
            "ada:UVFMImageCollection",
            "ada:VLMImageCollection",
            "ada:XANESCollection",
            "ada:XCTImageCollection"
          ]
        }
      }
    },
    "ada:memberTypes": {
      "allOf": [
        {
          "title": "String Array Type",
          "description": "Simple reusable array of strings",
          "type": "array",
          "minItems": 0,
          "items": {
            "type": "string"
          }
        },
        {
          "description": "List of the component types in the collection"
        }
      ]
    },
    "ada:nFiles": {
      "type": "integer",
      "description": "Number of files in the collection, including metadata files"
    },
    "ada:filelist": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ada:fileName": {
            "type": "string",
            "description": "Full path to file in container object"
          },
          "ada:fileNamePattern": {
            "type": "string",
            "description": "Pattern for collection members with differentiating suffix at '*'"
          },
          "ada:componentType": {
            "description": "The component type for the file(s)",
            "type": "string"
          },
          "schema:encodingFormat": {
            "type": "string",
            "description": "MIME type with extension"
          }
        },
        "oneOf": [
          {
            "required": [
              "ada:fileName"
            ]
          },
          {
            "required": [
              "ada:fileNamePattern"
            ]
          }
        ]
      }
    }
  }
}

=== usgin/geochemBuildingBlocks/build/tests/bbr/metadata/geochemProperties/collection/example_1_1.json
{
  "@type": [
    "ada:collection",
    "https://schema.org/Collection"
  ],
  "ada:componentType": {
    "@type": "ada:SEMEDSElementalMaps"
  },
  "ada:memberTypes": [
    "ada:SEMEDSElementalMap"
  ],
  "ada:nFiles": 5,
  "ada:filelist": [
    {
      "ada:fileName": "map_Fe_Ka.tif",
      "ada:componentType": "ada:SEMEDSElementalMap",
      "schema:encodingFormat": "image/tiff"
    },
    {
      "ada:fileName": "map_Si_Ka.tif",
      "ada:componentType": "ada:SEMEDSElementalMap",
      "schema:encodingFormat": "image/tiff"
    }
  ]
}
